### ISSUE TITLE
[Permissions] position of "default" causes permissions to be ignored.

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2416]
(I really didn't have a better title for this 😕)

When you have the ``default`` argument that's last on the ACL file. The ``default`` permission argument will be ignored. See the examples below.

Example with breaking behavior:
```yml
ping:
   role1: true
   role2: true
   default: false
```

Example with working behavior:
```yml
ping:
   default: false
   role1: true
   role2: true
```
