### ISSUE TITLE
`[p]permissions acl setguild` is broken for Postgres driver

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3796]
# Command bugs

#### Command name

`[p]permissions acl setguild`

#### What cog is this command from?

Permissions

#### What were you expecting to happen?

I expected ACL to be set properly

#### What actually happened?

The whole ACL for the guild got borked:
![image](https://user-images.githubusercontent.com/6032823/80323132-ccd88500-8829-11ea-8fc6-37e91ceb19f7.png)
- `default` and `176070082584248320` are keys that are result of using `[p]permissions acl setguild`
- `8` represents how it should look - the rule was added with a `[p]permissions addguildrule deny 8 57287406247743488` command right after setting ACL

For the reference, this is how YAML file given to `[p]permissions acl setguild` looks:
```yaml
COG: {}
COMMAND:
  ping:
    default: false
    176070082584248320: true
  roll:
    default: true
    176070082584248320: false
```

#### How can we reproduce this issue?

Use `[p]permissions acl setguild` on a bot using Postgres driver.
