### ISSUE TITLE
[Downloader] Support bootstrapping downloader repos and cogs from toml file

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#4063]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [X] API functionality

#### Describe your requested feature

Allowing downloader to bootstrap from an easy to use configuration file would be useful for both backup/restore as well as for container viability in the future. Ideally, this would be designed in a way that it could be used as both a command and a flag to the bot specifying a path to such a file. An export of current downloader state could also be useful with this.

an example toml which highlights why toml makes a nice expressive choice for this, and the sort of thing which would need to be stored.

```toml
[mine]
repo_url = "https://github.com/mikeshardmind/SinbadCogs/"
branch = "v3"

[mine.rolemanagement]
from_branch = false
hash = "44c2a7667a500c69a785d3ecd1ec5931609001ca"
pinned = true

[mine.autorooms]
from_branch = true
```
