### ISSUE TITLE
[Trivia] Add support for multiple choice

### ISSUE THREAD

**Issue by Hellioob** [Cog-Creators/Red-DiscordBot#4580]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Questions offering several answer options [A] [B] [C] [D] and false 👍 or true 👎
I upload sample images

![2020-11-05_23h17_28](https://user-images.githubusercontent.com/8948966/98303907-3dbdde00-1fbf-11eb-999c-3e15ab05fb12.png) ![2020-11-05_23h17_06](https://user-images.githubusercontent.com/8948966/98303913-40b8ce80-1fbf-11eb-9a57-70a7ac82ac81.png)

And an example of how I imagine adding questions to .yaml files
```
questions:
- question: Panic! At The Disco has currently released how many studio albums?
  correct_answer: '6'
  incorrect_answers:
  - '7'
  - '5'
  - '2'
- question: Vic Fuentes is the lead singer of Pierce The Veil.
  correct_answer: 'True'
  incorrect_answers:
-  'False'
```

Sorry for my bad English! I hope you understood me :)

**Comment by Kreusada** [comment]
I'm interested on working on this in the next couple of weeks. I think the best approach would be to add an additional key in the trivia list schema (i.e. `MODE`) to indicate the type of trivia list. This could be between "text" or "choice", for example. The `MODE` will determine how the trivia list is interpreted.

This opens up an additional point of discussion as to whether the choice mode still uses the fastest answer wins the round mechanic, or whether every player gets to answer under a specified timer and those who select the correct option are rewarded points when the timer expires (or when everyone has answered). It may feel unsatisfying to be presented with a selection of options and never have the capability to choose one, because someone else has already answered correctly first and the question has moved on. My thinking here is heavily inspired from the mechanics of [Kahoot!](https://kahoot.it).

A potential approach could be to introduce two new modes, with `choice` meaning that everyone gets an attempt to select an option, and `fastchoice` meaning the fastest player to select the correct option wins the round. Or, a singular mechanic is agreed upon that will always be used by `choice`.

All of the current settings available in `CONFIG` would be applicable with this new mode.

## New Mode Summary

**Proposal 1:**
- `text` - Text-based answers, how trivia has always been.
- `choice` - Multiple choice style trivia, everyone having the capability to submit an answer, *not* fastest correct answer wins.

**Proposal 2:**
- `text` - Text-based answers, how trivia has always been.
- `choice` - Multiple choice style trivia,  everyone having the capability to submit an answer.
- `fastchoice` - Multiple choice style trivia,  fastest correct answer select wins.

## Example Usage

Here's an example of how the `choice` (or respectively `fastchoice`) mode may be implemented within a trivia list. The ambiguity of the user response is removed through the use of buttons, so we can present differing options instead:

```yaml
AUTHOR: Kreusada
DESCRIPTION: Example trivia list
MODE: choice
A 2015 study found that what percentage of former American Football players had degenerative brain damage?:
- 65%
- 96%
- 23%
- 85%
```

## Button Interface
In terms of UI, the buttons could be presented with the label as the choice and the emoji with a coloured circle emoji that aligns with the index of the given option. For example, from these emojis `🔴 🔵 🟡 🟢 🟠 🟣 ⚫ ⚪ 🟤`, red would always represent option 1 and green would always represent option 4, etc. There should be a lower (2) and an upper (perhaps 6?) boundaries as to how many choices can be provided.

![Image](https://github.com/user-attachments/assets/67c4b303-0938-4153-ba24-6e841b301584)

An eval if you wish to reproduce:

```py
percentages = [65, 96, 23, 85]
emojis = ["🔴", "🔵", "🟡", "🟢"]
question = "A 2015 study found that what percentage of former American Football players had degenerative brain damage?"

view = discord.ui.View()

for emoji, percentage in zip(emojis, percentages):
    view.add_item(discord.ui.Button(label=f"{percentage}%", emoji=emoji))

await ctx.send(question, view=view)
```

Feel free to discuss in this issue if you have any suggestions about how the forementioned ideas are implemented.
