### ISSUE TITLE
Permissions: Overwrites doesn't work after restart or reload when setting an alias

### ISSUE THREAD

**Issue by Luc1412** [Cog-Creators/Red-DiscordBot#4896]
### What Red version are you using?

3.4.7

### What were you trying to do?

I got the following configuration:

```yml
COG:
  ExampleCommandCog:
    default: false
    419172192283131905: true
    400024739441147907: true
COMMAND:
  example:
    406942236635299841: true
    422122307473899530: true
```

### What did you expect to happen?

The command will be accessible in `406942236635299841` for everyone.

### What actually happened?

The command is accessible to everyone, but after some time (or a restart/cog reload) it stops working.

When I check the acl server config, the settings are still there, but somehow not active. After getserver and uploading the same config with setserver the permissions start working again,

### How can we reproduce this error?

1. [p]permissions acl getserver
2. Configure it as mentioned above
3. Upload the config with [p]permissions acl setserver
-> It works
4. Restart the bot or reload the cog or some other unknown trigger
5. It stops working until repeating step 1 and 3

EDIT:
### Important notice
After further investigation, I noticed that this **only happens if the command is an alias**. Not sure if it is still worth investigating and fixing it.
