### ISSUE TITLE
Audio Filter/EQ presets (Post your own)

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#5060]
Hey y'all ahead of it being added to core i wanna gather a few presets so that they can be bundled with audio.

Pleasee add your suggestions here in the following format:

```yaml
Nightcore:
  - Timescale:
      - Speed: 1.2
      - Pitch: 1.2
      - Rate: 1.0
  - EQ:
  	  - Band 1: -0.1
  	  - Band 2: 0.125
  	  - Band 3: 0.125
```
